FROM python:3.11.4-alpine3.18 as requirements-stage

WORKDIR /tmp
RUN pip install poetry==1.5.1
COPY ./pyproject.toml ./poetry.lock* /tmp/
RUN poetry export --with dev -f requirements.txt --output requirements.txt --without-hashes

FROM python:3.11.4-alpine3.18

RUN apk update \
    && apk add --no-cache \
    curl

ENV PYTHONDONTWRITEBYTECODE 1
ENV APP_HOME /home/user/app
RUN mkdir -p $APP_HOME
WORKDIR $APP_HOME
COPY --from=requirements-stage /tmp/requirements.txt /home/user/requirements.txt
RUN pip install --no-cache-dir -r /home/user/requirements.txt

CMD ["/bin/sh", "-c", "python manage.py runserver"]
