version: "3.8"

x-env: &env
  environment:
    DATABASE_URL: postgres://test_user:test_password@db_dev:5432/postgres_dev
    RABBITMQ_URL: pyamqp://guest@message_broker_dev//
    SECRET_KEY: "bj4wa_n7usp9^sycla5(6k-!yd=s=%ze(log_)fkx5n3u+=b@g"
    DJANGO_HOST: "localhost"
    DEBUG: "true"
  env_file:
    - .env.local.dev


services:
  backend:
    <<: *env
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/home/user/app/
    ports:
      - 8000:8000

  celery_worker:
    <<: *env
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/home/user/app/
    command: >
      sh -c "python -m celery -A unbosque_calendar worker -l INFO -E"

  celery_beat:
    <<: *env
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/home/user/app/
    command: >
      sh -c "python -m celery -A unbosque_calendar beat"

  db_dev:
    image: "postgres:15.3-alpine"
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: postgres_dev
    volumes:
      - pgdata_dev:/var/lib/postgresql/data:rw
    ports:
      - 8004:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "test_user", "-d", "postgres_dev"]
      interval: 30s
      timeout: 3s
      retries: 30
      start_period: 15s

  message_broker_dev:
    image: "rabbitmq:3.12.0-alpine"
    ports:
      - 8005:5672

volumes:
  pgdata_dev: